# Umbriel general settings
# Includes converted values from Hyprland config

[general]
autostart = [
  "noctalia",
  # "dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE",
]
mod_key = "Alt"
xwayland = true
show_cheatsheet = true
focus_on_activate = false
honor_restored_maximize = false

[environment]
XCURSOR_SIZE = "24"
XCURSOR_THEME = "Bibata-Modern-Classic"
GDK_BACKEND = "wayland,x11,*"
GDK_SCALE = "1"
SDL_VIDEODRIVER = "wayland"
MOZ_ENABLE_WAYLAND = "1"
ELECTRON_OZONE_PLATFORM_HINT = "auto"
# Safe Nvidia environment variables (enabled automatically if Nvidia GPU is detected)
# LIBVA_DRIVER_NAME = "nvidia"
# __GLX_VENDOR_LIBRARY_NAME = "nvidia"

