[input]
middle_click_paste = false

[input.keyboard]
repeat_rate = 25
repeat_delay = 600

[input.mouse]
natural_scroll = false
accel_profile = "flat"
sensitivity = 0.0
scroll_wheel_step = 60

[input.cursor]
theme = "Bibata-Modern-Classic"
size = 24    # 1-512
hardware_cursor = true
follows_focus = true
hide_when_typing = false
hide_timeout_ms = 0

[input.focus]
follows_mouse = true
# follows_mouse_max_scroll = 0.5  # optional, measured in viewport widths
