# ----------------------------------------------------------------------------
# All window rules
# ----------------------------------------------------------------------------
[[window_rule]]
match.app_id = ".*"
opacity = 0.97
# blur = true
# blur_optimized = true

# ----------------------------------------------------------------------------
# Steam Rules
# ----------------------------------------------------------------------------
# All Steam windows: always floating and 100% opaque (no blur/transparency artifacts)
[[window_rule]]
match.app_id = "^steam.*$"
default_floating = true
opacity = 1.0

# Main Steam client window size & placement
[[window_rule]]
match.app_id = "^steam$"
match.title = "^Steam$"
default_size = [1100, 700]
default_position = { x = 0, y = 0, anchor = "center" }

# Steam Friends list size
[[window_rule]]
match.app_id = "^steam$"
match.title = "^Friends List$"
default_size = [460, 800]

# ----------------------------------------------------------------------------
# Dialogs & Utilities
# ----------------------------------------------------------------------------
# File pickers & transfer dialogs
[[window_rule]]
match.title = "^(Open File|Select|Choose a wallpaper|Open Folder|Save As|Library|Choose Where to Download|File Operation Progress|Rename|Copy Files|Move Files|Search Files)$"
default_floating = true

# Satty (Screenshot annotation)
[[window_rule]]
match.app_id = "^com.gabm.satty$"
default_floating = true
default_pinned = true
default_size = [460, 800]
default_position = { x = 0, y = 0, anchor = "center" }

# ----------------------------------------------------------------------------
# Desktop Shell (Noctalia)
# ----------------------------------------------------------------------------
# Blur all Noctalia bars, panels, notifications, and popups
[[layer_rule]]
match.namespace = "^noctalia-.*"
blur = true
blur_ignore_alpha = 0.5
blur_popups = true


# [[window_rule]]
# match.app_id = "^(kitty)$"
# blur = true
# blur_optimized = true
