[workspaces]
back_and_forth = false
empty_above = false

[output.DP-1]
mode = "1920x1080@180"
position = [0, 0]
scale = 1

[layout]
mode = "dwindle"        # "scrolling", "dwindle", or "master"
gap = 5
# width_presets = [0.333, 0.5, 0.667]

[layout.scrolling]
default_width_fraction = 0.5
center_underfull_strip = true
center_focused = false
expand_single_column = true

[layout.dwindle]
preserve_split = true

[layout.master]
position = "left"
default_width_fraction = 0.55
new_on_top = true

[overview]
zoom = 0.5

[hot_corners.top_left]
enabled = true
delay_ms = 200
action = "overview-open"
