[workspaces]
back_and_forth = true
empty_above = false

[output.DP-1]
mode = "1920x1080@180"
position = [0, 0]
scale = 1

[layout]
mode = "dwindle"
gap = 5

[layout.dwindle]
preserve_split = true

[layout.scrolling]
default_width_fraction = 0.5
center_underfull_strip = true
center_focused = false
expand_single_column = true

[layout.master]
position = "left"
default_width_fraction = 0.55
new_on_top = true

[overview]
zoom = 0.5
background_blur = false
shortcuts = false

[hot_corners.top_left]
enabled = true
delay_ms = 200
action = "overview-open"
