# Font
font_family MapleMono
bold_italic_font auto
font_size        14.0
background_opacity 0.7
scrollback_indicator_opacity 0.0
cursor_trail 1

# Window
window_padding_width 14
window_padding_height 14
hide_window_decorations yes
show_window_resize_notification no
confirm_os_window_close 0

# Allow remote access
single_instance no
allow_remote_control no

# Aesthetics
cursor_shape block
enable_audio_bell no

# Minimal Tab bar styling
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}
