local M = {}

-- Parse the 16-color palette generated by Noctalia for Kitty
function M.load_kitty_palette()
  local path = vim.fn.expand("~/.config/kitty/themes/noctalia.conf")
  local f = io.open(path, "r")
  if not f then
    return nil
  end
  local c = {}
  for line in f:lines() do
    local key, val = line:match("^([%w_]+)%s+(#[%x]+)")
    if key and val then
      c[key] = val
    end
  end
  f:close()

  return {
    base00 = c.background or "#1a1a23",
    base01 = c.color0 or "#212230",
    base02 = c.selection_background or c.color0 or "#212230",
    base03 = c.color8 or "#646574",
    base04 = c.selection_foreground or "#afafb6",
    base05 = c.foreground or "#f2f2f3",
    base06 = c.color15 or "#f2f2f3",
    base07 = c.color7 or "#f2f2f3",
    base08 = c.color1 or "#fd4663",
    base09 = c.color3 or "#9679b9",
    base0A = c.color4 or "#b679b9",
    base0B = c.color2 or "#8a8cc2",
    base0C = c.color6 or "#bdabd3",
    base0D = c.color4 or "#b679b9",
    base0E = c.color5 or "#abadd3",
    base0F = c.color5 or "#abadd3",
  }
end

-- Apply the palette, telescope highlights, transparency, and statusline
function M.apply()
  local palette = M.load_kitty_palette()
  if not palette then
    return
  end

  local ok, base16 = pcall(require, "base16-colorscheme")
  if not ok then
    return
  end

  base16.setup(palette)

  -- Highlights for Telescope
  local hi = function(group, opts)
    vim.api.nvim_set_hl(0, group, opts)
  end
  hi("TelescopeNormal", { fg = palette.base05, bg = palette.base00 })
  hi("TelescopeBorder", { fg = palette.base03, bg = palette.base00 })
  hi("TelescopePromptNormal", { fg = palette.base05, bg = palette.base00 })
  hi("TelescopePromptBorder", { fg = palette.base03, bg = palette.base00 })
  hi("TelescopePromptPrefix", { fg = palette.base0B, bg = palette.base00 })
  hi("TelescopePromptCounter", { fg = palette.base04, bg = palette.base00 })
  hi("TelescopePromptTitle", { fg = palette.base00, bg = palette.base0B })
  hi("TelescopePreviewTitle", { fg = palette.base00, bg = palette.base0A })
  hi("TelescopeResultsTitle", { fg = palette.base00, bg = palette.base09 })
  hi("TelescopeSelection", { fg = palette.base05, bg = palette.base02 })
  hi("TelescopeSelectionCaret", { fg = palette.base0B, bg = palette.base02 })
  hi("TelescopeMatching", { fg = palette.base0B, bold = true })

  -- Transparent background (preserves foreground color while removing background)
  local transparent_groups = {
    "Normal",
    "NormalNC",
    "NormalFloat",
    "FloatBorder",
    "SignColumn",
    "FoldColumn",
    "LineNr",
    "CursorLineNr",
    "EndOfBuffer",
  }
  for _, g in ipairs(transparent_groups) do
    local def = vim.api.nvim_get_hl(0, { name = g, link = false })
    def.bg = nil
    def.ctermbg = nil
    vim.api.nvim_set_hl(0, g, def)
  end

  -- Refresh lualine with the updated base16 palette (only if already loaded)
  if package.loaded["lualine"] then
    local lualine = require("lualine")
    pcall(lualine.setup, { options = { theme = "base16" } })
  end
end

-- Start background watcher for Kitty theme updates (triggers live on wallpaper change)
function M.setup_watcher()
  if _G.__kitty_theme_watcher then
    return
  end

  local dir = vim.fn.expand("~/.config/kitty/themes")
  local watcher = vim.uv.new_fs_event()
  if watcher then
    watcher:start(
      dir,
      {},
      vim.schedule_wrap(function(err, fname)
        if not err and (fname == "noctalia.conf" or fname == nil) then
          M.apply()
        end
      end)
    )
    _G.__kitty_theme_watcher = watcher
  end

  -- Also listen for SIGUSR1 if triggered
  if not _G.__kitty_theme_signal then
    local signal = vim.uv.new_signal()
    _G.__kitty_theme_signal = signal
    signal:start(
      "sigusr1",
      vim.schedule_wrap(function()
        M.apply()
      end)
    )
  end

  -- Refresh on FocusGained
  vim.api.nvim_create_autocmd("FocusGained", {
    callback = function()
      M.apply()
    end,
  })
end

return {
  {
    "RRethy/base16-nvim",
    lazy = false,
    priority = 1000,
    config = function()
      M.apply()
      M.setup_watcher()
    end,
  },
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = function()
        M.apply()
      end,
    },
  },
  {
    "nvim-lualine/lualine.nvim",
    opts = function(_, opts)
      opts.options = opts.options or {}
      opts.options.theme = "base16"
    end,
  },
}
