[mgr]
show_hidden = true

[[plugin.prepend_fetchers]]
url   = "*"
run   = "git"
group = "git"

[[plugin.prepend_fetchers]]
url   = "*/"
run   = "git"
group = "git"

[plugin]

[opener]
image = [
    { run = 'imv %s', orphan = true, desc = "View image with imv" },
]
video = [
    { run = 'mpv %s', orphan = true, desc = "Play with mpv" },
]
audio = [
    { run = 'mpv --no-video %s', orphan = true, desc = "Play audio with mpv" },
]

[open]
prepend_rules = [
    # Images -> imv
    { mime = "image/*", use = "image" },

    # Videos & Audio -> mpv
    { mime = "video/*", use = "video" },
    { mime = "audio/*", use = "audio" },
]
