color0 #2f222c
color1 #fd4663
color2 #c18bb3
color3 #be7481
color4 #ad8f85
color5 #d3acc9
color6 #d6a8b0
color7 #f3f2f3
color8 #72636e
color9 #fd4663
color10 #c18bb3
color11 #be7481
color12 #ad8f85
color13 #d3acc9
color14 #d6a8b0
color15 #f3f2f3

cursor                #f3f2f3
cursor_text_color     #231a21
background            #231a21
foreground            #f3f2f3
selection_foreground  #b6afb4
selection_background  #2f222c
active_border_color   #c18bb3
inactive_border_color #2f222c
url_color             #c18bb3

active_tab_foreground   #221b20
active_tab_background   #c18bb3
inactive_tab_foreground #b6afb4
inactive_tab_background #2f222c
cursor_trail_color      #b6afb4
