palette = "noctalia"
# add_newline = false

format = """
[](yellow)\
$os\
$username\
[](bg:blue fg:yellow)\
$directory\
[](fg:blue bg:cyan)\
$git_branch\
$git_status\
[](fg:cyan bg:green)\
[ 󰭟 ](bg:green fg:black)\
[ ](fg:green)\
$line_break\
$character"""

[username]
show_always = true
style_user = "bg:yellow fg:black bold"
style_root = "bg:red fg:black bold"
format = '[$user ]($style)'
disabled = false

[os]
style = "bg:yellow fg:black"
disabled = true

[directory]
style = "bg:blue fg:black bold"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = " "
style = "bg:cyan fg:black bold"
format = '[ $symbol$branch ]($style)'

[git_status]
style = "bg:cyan fg:black bold"
format = '[$all_status$ahead_behind ]($style)'

[character]
disabled = false
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold magenta)"

# >>> NOCTALIA STARSHIP PALETTE >>>
# Noctalia Starship Palette
# Generated by Noctalia - do not edit manually

[palettes.noctalia]
# Standard colors
blue      = "#a8c476"
red       = "#ee864c"
green     = "#d79875"
yellow    = "#c9bd71"
cyan      = "#dcd4a3"
magenta   = "#deb7a1"
white     = "#f3f2f2"
black     = "#302721"

# Extended palette (Catppuccin-compatible names)
rosewater = "#c9bd71"
flamingo  = "#ee864c"
pink      = "#deb7a1"
mauve     = "#deb7a1"
maroon    = "#ee864c"
peach     = "#c9bd71"
teal      = "#dcd4a3"
sky       = "#dcd4a3"
sapphire  = "#a8c476"
lavender  = "#deb7a1"

# Text shades
text      = "#f3f2f2"
subtext1  = "#f3f2f2"
subtext0  = "#716761"

# Surface shades
overlay2  = "#716761"
overlay1  = "#716761"
overlay0  = "#302721"
surface2  = "#302721"
surface1  = "#302721"
surface0  = "#231d1a"
base      = "#231d1a"
mantle    = "#231d1a"
crust     = "#231d1a"
# <<< NOCTALIA STARSHIP PALETTE <<<
