palette = "noctalia"

format = """
[](red)\
$os\
$username\
[](bg:yellow fg:red)\
$directory\
[](bg:cyan fg:yellow)\
$git_branch\
$git_status\
[](fg:cyan bg:blue)\
[](fg:blue bg:magenta)\
[](fg:magenta bg:green)\
[ 󰭟 ](bg:green fg:black)\
[ ](fg:green)\
$line_break\
$character"""

[username]
show_always = true
style_user = "bg:red fg:black bold"
style_root = "bg:red fg:black bold"
format = '[$user ]($style)'
disabled = false

[os]
style = "bg:red fg:black"
disabled = true

[directory]
style = "bg:yellow fg:black bold"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = " "
style = "bg:cyan fg:black bold"
format = '[ $symbol$branch ]($style)'

[git_status]
style = "bg:cyan fg:black bold"
format = '[$all_status$ahead_behind ]($style)'

[character]
disabled = false
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold magenta)"

# >>> NOCTALIA STARSHIP PALETTE >>>
# Noctalia Starship Palette
# Generated by Noctalia - do not edit manually

[palettes.noctalia]
# Standard colors
blue      = "#a7ad85"
red       = "#fd4663"
green     = "#c1938b"
yellow    = "#c46ea0"
cyan      = "#daa4c4"
magenta   = "#ccaec3"
white     = "#f2f2f3"
black     = "#2e2f24"

# Extended palette (Catppuccin-compatible names)
rosewater = "#c46ea0"
flamingo  = "#fd4663"
pink      = "#ccaec3"
mauve     = "#ccaec3"
maroon    = "#fd4663"
peach     = "#c46ea0"
teal      = "#daa4c4"
sky       = "#daa4c4"
sapphire  = "#a7ad85"
lavender  = "#ccaec3"

# Text shades
text      = "#f2f2f3"
subtext1  = "#f2f2f3"
subtext0  = "#6f6e61"

# Surface shades
overlay2  = "#6f6e61"
overlay1  = "#6f6e61"
overlay0  = "#2e2f24"
surface2  = "#2e2f24"
surface1  = "#2e2f24"
surface0  = "#22231c"
base      = "#22231c"
mantle    = "#22231c"
crust     = "#22231c"
# <<< NOCTALIA STARSHIP PALETTE <<<
